scorecard:
  # Setting a global scorecard option
  bundle: deploy/olm-catalog/ibm-healthcheck-operator
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-healthcheck-operator/3.8.3/ibm-healthcheck-operator.v3.8.3.clusterserviceversion.yaml"
