apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mustgatherjobs.operator.ibm.com
  labels:
    app.kubernetes.io/instance: ibm-healthcheck-operator
    app.kubernetes.io/managed-by: ibm-healthcheck-operator
    app.kubernetes.io/name: ibm-healthcheck-operator
spec:
  group: operator.ibm.com
  names:
    kind: MustGatherJob
    listKind: MustGatherJobList
    plural: mustgatherjobs
    singular: mustgatherjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MustGatherJob is the Schema for the mustgatherjobs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MustGatherJobSpec defines the desired state of MustGatherJob
          properties:
            image:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                must gather image'
              properties:
                pullPolicy:
                  description: image pull policy, default is IfNotPresent
                  type: string
                repository:
                  description: image repository, default is empty
                  type: string
                tag:
                  description: image tag, default is empty
                  type: string
              required:
              - repository
              - tag
              type: object
            mustgatherCommand:
              description: must gather command, default is gather
              type: string
            mustgatherConfigName:
              description: must gather config name, default is default
              type: string
            serviceAccountName:
              description: must gather job ServiceAccountName, default is default
              type: string
          type: object
        status:
          description: MustGatherJobStatus defines the observed state of MustGatherJob
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
